### ISSUE TITLE
Melhora do xkcd: pegar ordem inversa de comics

### ISSUE THREAD

**Issue by Zengor** [tfagit/telegram-bot#15]
Como a sintaxe de listas em python:
`!xkcd -1` retornaria a última comic
`!xkcd -2` a penúltima
e assim por diante

**Comment by ghost** [comment]
O commit cffce97d5ad16dfa0cbef07 deveria ter resolvido isso, mas por algum motivo esse commit faz o !xkcd parar de interpretar as ids que são repassadas pra ele.

**Comment by ghost** [comment]
Solucionado com os commits c80fcc7340be44b e 59e608dfaeebe33e84dad33.
