### ISSUE TITLE
Otimizar triggers do roll.lua

### ISSUE THREAD

**Issue by ghost** [tfagit/telegram-bot#18]
Para acelerar o processo de rolamentos, as triggers do roll.lua poderiam ser baseadas na própria notação de dados. 
Por exemplo: `!roll 1d20` vira `!1d20`.

**Comment by Hybbon** [comment]
https://github.com/tfagit/telegram-bot/commit/ab0468a9c4b55ac19d2afb18cdb8e025a53ef20a

Resolvido.
