### ISSUE TITLE
Mudar o comando de uso

### ISSUE THREAD

**Issue by loloop** [tfagit/telegram-bot#3]
Mudar o ! dos comandos para # como originalmente requisitado

**Comment by Zengor** [comment]
Isso é realmente necessário?

**Comment by loloop** [comment]
Sim

**Comment by ghost** [comment]
Eu prefiro deixar os comandos utilizando a exclamação, o DuckDuckGo também usa comandos com exclamações então você já tem um padrão se formando. Fora que mudar o padrão que já é usado pelo projeto original é algo bem desagradável porque você vai ter de alterar a maioria dos plugins.

**Comment by Zengor** [comment]
Também prefiro `!`, mas é trivial adicionar mais patterns, então só botei as patterns com `#`, sem remover as `!`.  Se a gente não vai usar um plugin, também não tem porque tocar nele.
Agora é só lembrar de colocar ambas as patterns nos plugins futuros.

**Comment by loloop** [comment]
@japareaggae o lance é que eu falei que eu ia dar o número de celular pra um bot que usasse `#`, não pra um bot.
