### ISSUE TITLE
Alteração: retorno de !guii

### ISSUE THREAD

**Issue by Zengor** [tfagit/telegram-bot#8]
Debatam as vantagens e desvantagens de trocar o valor de `!guii` para retornar 'www.google.com.br'

**Comment by loloop** [comment]
Acho que é mais fácil habilitar o `#google` (mas daí altera pra ele não retornar tanta coisa) e deixar o `#guii` do jeito que está

**Comment by Zengor** [comment]
Mas a ideia é ser cuzão com o Gui, então acho bem mais apropriado retornar o endereço do google. Assim talvez ele aprenda a pesquisar as coisas sozinho

**Comment by hugoanjos** [comment]
mas nem sempre google.com.br responde o gui como um bom e velho vai se foder

**Comment by loloop** [comment]
@hugoanjos pensando bem na real isso tem que ser automático, agora eu apoio a ideia do google.com.br
Quem sabe até um lmgtfy?

**Comment by Zengor** [comment]
Já tem um automatizado que responde a 4 mensagens seguidas do Gui com "CALA A BOCA, GUI"
Só falta ele aparecer pra settarmos o id dele no config

**Comment by Zengor** [comment]
Bem, adicionei um lmgtfy.lua, então acho que não é mais necessário mudar o valor de `!guii`
