### ISSUE TITLE
Plugins retornando mensagem direta

### ISSUE THREAD

**Issue by loloop** [tfagit/telegram-bot#9]
Uns plugins tipo o `#help` e coisas do tipo assim que listam deveriam retornar a resposta numa mensagem direta pra quem enviou o comando pra não gerar aquele clutter desnecessário no chat principal, não acham?

**Comment by Hybbon** [comment]
https://github.com/tfagit/telegram-bot/commit/d199f696ea4886d52858b1f6bee649df99f447fd
